apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor-ui-deployment
  namespace: orchestration-layer
  labels:
    app: conductor-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conductor-ui
      type: conductor-ui
  template:
    metadata:
      name: conductor-ui-pod
      labels:
        app: conductor-ui
        type: conductor-ui
    spec:
      containers:
        - name: conductor-ui
          image: sebinmaret/conductor-ui:1
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "0.4"
              memory: "800Mi"
            requests:
              cpu: "0.2"
              memory: "300Mi"
          ports:
            - containerPort: 5000
          env: 
            - name: WF_SERVER
              value: conductor-server:8080
            

---
apiVersion: v1
kind: Service
metadata: 
  name: conductor-ui
  namespace: orchestration-layer
  labels:
    app: conductor-ui
    type: conductor-ui-service
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 31516
  selector:
    app: conductor-ui
    type: conductor-ui

# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: workflow-registration
#   namespace: orchestration-layer
# spec:
#   template:
#     spec:
#       containers:
#       - name: workflow-registration
#         image: sebinmaret/conductor-registration:1
#         env: 
#           - name: CONDUCTOR_SERVER_IP
#             value: "conductor-server.orchestration-layer"
#           - name: CONDUCTOR_SERVER_PORT
#             value: "80"
#       restartPolicy: Never
#   backoffLimit: 4