apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-service-rest-deployment
  namespace: orchestration-layer
  labels:
    app: contact-service-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-service-rest
      type: contact-service-rest
  template:
    metadata:
      name: contact-service-rest
      labels:
        app: contact-service-rest
        type: contact-service-rest
    spec:
      containers:
        - name: contact-service-rest
          image: sidharthsunilkumar/contact-service-rest:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata: 
  name: contact-service-rest
  namespace: orchestration-layer
  labels:
    app: contact-service-rest
    type: contact-service-service-rest
spec:
  type: ClusterIP
  ports:
    - targetPort: 8081
      port: 8081
  selector:
    app: contact-service-rest
    type: contact-service-rest