apiVersion: v1
kind: Namespace
metadata:
  name: orchestration-layer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: orchestration-layer
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: elasticsearch
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        app: myapp
        type: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elastic
          # image: sebinmaret/elasticsearch:1
          ports:
            - containerPort: 9300
            - containerPort: 9200
          env: 
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: transport.host
              value: "0.0.0.0"
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"

---
apiVersion: v1
kind: Service
metadata: 
  name: es
  namespace: orchestration-layer
  labels:
    app: myapp
    type: elasticsearch-service
spec:
  type: ClusterIP
  ports:
    - name: tcp
      targetPort: 9300
      port: 9300
    - name: http
      targetPort: 9200
      port: 9200
  selector:
    app: myapp
    type: elasticsearch