# apiVersion: v1
# kind: Namespace
# metadata:
#   name: orchestration-layer
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-service-deployment
  namespace: orchestration-layer
  labels:
    app: helloworld-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-service
      type: helloworld-service
  template:
    metadata:
      name: helloworld-service
      labels:
        app: helloworld-service
        type: helloworld-service
    spec:
      containers:
        - name: helloworld-service
          image: sidharthsunilkumar/helloworld-python:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata: 
  name: helloworld-service
  namespace: orchestration-layer
  labels:
    app: helloworld-service
    type: helloworld-service-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: helloworld-service
    type: helloworld-service