apiVersion: apps/v1
kind: Deployment
metadata:
  name: namedemo-service-deployment
  namespace: orchestration-layer
  labels:
    app: namedemo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namedemo-service
      type: namedemo-service
  template:
    metadata:
      name: namedemo-service
      labels:
        app: namedemo-service
        type: namedemo-service
    spec:
      containers:
        - name: namedemo-service
          image: sidharthsunilkumar/namedemo-service:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata: 
  name: namedemo-service
  namespace: orchestration-layer
  labels:
    app: namedemo-service
    type: namedemo-service-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8081
      port: 8081
  selector:
    app: namedemo-service
    type: namedemo-service