apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-deployment
  # namespace: orchestration-layer
  labels:
    app: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
      type: wiremock
  template:
    metadata:
      name: wiremock-pod
      labels:
        app: wiremock
        type: wiremock
    spec:
      containers:
        - name: wiremock
          image: ektabansal/wiremock:v2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: wiremock
  # namespace: orchestration-layer
  labels:
    app: wiremock
    type: wiremock
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: wiremock
    type: wiremock